name: Coverage

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Dart tests and collect coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.DLIBPHONENUMBER_TOKEN }}

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Run tests with coverage
        run: |
          dart pub global activate coverage
          dart test --coverage=coverage
          dart pub global run coverage:format_coverage \
            --lcov --in=coverage --out=coverage.lcov \
            --packages=.dart_tool/package_config.json \
            --report-on=lib

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
